PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbo: <dbpedia.org/onthology/>
PREFIX dbp: <dbpedia.org/property/>
PREFIX doap: <http://usefulinc.com/ns/doap#>

# Person
CONSTRUCT {
    ?URI a dbo:Person;
    foaf:firstName ?prenom;
    foaf:familyName ?nom;
    foaf:gender ?sexe;
    <http://concours-etoiles-europe.org/ns#Award_Won> ?AwardWon;
    #<http://concours-etoiles-europe.org/ns#codeSexe> ?Code_sexe;
}
FROM <file:fr-esr-etoile-de-l-europe.csv> 
WHERE{
    BIND (URI(CONCAT('http://concours-etoiles-europe.org/ns#', ?prenom, '-' ,?nom)) AS ?URI)
    BIND (URI(CONCAT('http://concours-etoiles-europe.org/ns#', ?Type_de_prix, ?nom)) AS ?AwardWon)
}

# Projet
CONSTRUCT {
    ?URI a doap:Project;
    doap:maintainer ?person;
    doap:name ?Titre_du_projet;
    doap:homepage ?Lien_Cordis;
    doap:description ?Résumé;
    doap:category ?Thematique;
    ?TypeFinancement ?Type_financement;
    ?CodeProgramme ?Code_du_programme;
    ?CodeAppel ?Code_d_appel_à_projet;
    ?AcronymeProjet ?Acronyme_du_projet;
}
FROM <file:fr-esr-etoile-de-l-europe.csv> 
WHERE{
    BIND (URI(CONCAT('http://concours-etoiles-europe.org/ns#', ?prenom, '-' ,?nom)) AS ?person)
    BIND (URI(CONCAT('http://concours-etoiles-europe.org/ns#', ?Titre_du_projet)) AS ?URI)

    BIND (URI('http://concours-etoiles-europe.org/ns#Type_financement') AS ?TypeFinancement)
    BIND (URI('http://concours-etoiles-europe.org/ns#Code_du_programme') AS ?CodeProgramme)
    BIND (URI('http://concours-etoiles-europe.org/ns#Code_d_appel_à_projet') AS ?CodeAppel)
    BIND (URI('http://concours-etoiles-europe.org/ns#Acronyme_du_projet') AS ?AcronymeProjet)
}

# AwardWon
CONSTRUCT {
    ?URI a <http://concours-etoiles-europe.org/ns#Award_Won>;
    dbo:Award ?Type_de_prix;
    ?AwardMention ?Mention; 
    ?NumEdition ?Numéro_de_l_édition;
    ?AwardEdition ?Edition;
    ?AwardPlace ?URICommune
}
FROM <file:fr-esr-etoile-de-l-europe.csv> 
WHERE{       
    BIND (URI(CONCAT('http://concours-etoiles-europe.org/ns#', ?Type_de_prix, ?nom)) AS ?URI)
    
    BIND (URI('http://concours-etoiles-europe.org/ns#Mention') AS ?AwardMention)
    BIND (URI('http://concours-etoiles-europe.org/ns#Numéro_de_l_édition') AS ?NumEdition)
    BIND (URI('http://concours-etoiles-europe.org/ns#Edition') AS ?AwardEdition)
    BIND (URI(CONCAT('http://dbpedia.org/page/', ?Libellé_commune)) AS ?URICommune)
}


