PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX doap: <http://usefulinc.com/ns/doap#>
PREFIX owl: <http://www.w3.org/2002/07/owl>
PREFIX nous: <http://concours-etoiles-europe.org/ns>

# Person
CONSTRUCT {
    ?URI a dbo:Person;
    foaf:firstName ?prenom;
    foaf:familyName ?nom;
    foaf:gender ?sexe;
    nous:id_ref ?IdRef;
    owl:sameAs ?Lien_IdRef;
    nous:Award_Won ?AwardWon;
}
FROM <file:fr-esr-etoile-de-l-europe.csv> 
WHERE{
    BIND (URI(CONCAT('http://concours-etoiles-europe.org/ns#', ?prenom, '-' ,?nom)) AS ?URI)
    BIND (URI(CONCAT('http://concours-etoiles-europe.org/ns#', ?Type_de_prix, ?nom)) AS ?AwardWon)
}

# Projet
CONSTRUCT {
    ?URI a doap:Project;
    doap:maintainer ?person;
    doap:name ?Titre_du_projet;
    doap:homepage ?Lien_Cordis;
    doap:description ?Résumé;
    doap:category ?Thematique;
    nous:type_financement ?Type_financement;
    nous:code_programme ?Code_du_programme;
    nous:code_appel ?Code_d_appel_à_projet;
    nous:acronyme_projet ?Acronyme_du_projet;    
    foaf:Organization ?URI_Structure
}
FROM <file:fr-esr-etoile-de-l-europe.csv> 
WHERE{
    BIND (URI(CONCAT('http://concours-etoiles-europe.org/ns#', ?prenom, '-' ,?nom)) AS ?person)
    BIND (URI(CONCAT('http://concours-etoiles-europe.org/ns#', ?Titre_du_projet)) AS ?URI)

    BIND (URI(CONCAT('http://concours-etoiles-europe.org/ns#', ?Libellé_de_structure)) AS ?URI_Structure)
}


# Organization
CONSTRUCT {
    ?URI a foaf:Organization;
    nous:identifiant_structure ?Identifiant_de_structure;
    nous:libelle_structure ?Libellé_de_structure;
    nous:sigle_structure ?Sigle_de_structure;
    nous:nature_structure ?Nature_de_la_structure;
    owl:sameAs ?Lien_scanR;
    dbo:Settlement ?URI_Commune;
}
FROM <file:fr-esr-etoile-de-l-europe.csv> 
WHERE{
    BIND (URI(CONCAT('http://concours-etoiles-europe.org/ns#', ?Libellé_de_structure)) AS ?URI)
    BIND (URI(CONCAT('http://dbpedia.org/page/', ?Libellé_commune)) AS ?URI_Commune)

}


# AwardWon
CONSTRUCT {
    ?URI a nous:Award_Won;
    dbo:Award ?Type_de_prix;
    nous:mention ?Mention; 
    nous:numero_edition ?Numéro_de_l_édition;
    nous:edition ?Edition;  
}
FROM <file:fr-esr-etoile-de-l-europe.csv> 
WHERE{       
    BIND (URI(CONCAT('http://concours-etoiles-europe.org/ns#', ?Type_de_prix, ?nom)) AS ?URI)
}
