PREFIX foaf:  <http://xmlns.com/foaf/0.1/> 
PREFIX doap: <http://usefulinc.com/ns/doap#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX nous: <http://concours-etoiles-europe.org/ns#>

# Retourne le nom de tous les vainqueurs du concours de l'année 2016 et leur mention si renseignée

SELECT ?firstName ?familyName ?mention
WHERE{
    ?x foaf:firstName ?firstName ;
       foaf:familyName ?familyName;
        schema:award ?award.
  
    ?award nous:edition "2016".
    OPTIONAL{
        ?award nous:mention ?mention .
    }    
}

# Retourne les années où l'award a été décerné à un.e parisien.ne ainsi que son prénom et son nom

SELECT ?year ?firstName ?familyName 
WHERE{
    ?person schema:award ?award;
            foaf:firstName ?firstName;
            foaf:familyName ?familyName.
    ?award nous:edition ?year.    
  
    ?project dbo:creator ?person;
       dbo:creator ?firm.   
    
  
    ?firm rdf:type foaf:Organization;
     dbo:location ?location.
  
    ?location foaf:name ?name.
    FILTER regex(?name,".*Paris.*")
}

# Le nombre de projet lauréats en fonction du type de la structure

SELECT ?nat (count(distinct ?projet) as ?nb_projets)
WHERE {
    ?projet nous:nature_structure ?nat.
} GROUP BY ?nat ORDER BY ?nb_projets

# Query inter-groupes // Retourne tous les "Pierre" qui ont reçu un prix

SELECT ?firstName ?familyName
FROM NAMED <http://concours-etoiles-europe.org/ns#>
FROM NAMED <http://leurs-data/data#>
WHERE{
    ?x foaf:firstName ?firstName;
        foaf:familyName ?familyName;
        foaf:firstName “Pierre” .
}

